# Generated by Django 4.2.3 on 2023-07-27 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=10, verbose_name='Telefone'),
        ),
    ]
